// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDE97NcxTzgXbwa3sSuJy0BgCyJuNgYQ',
    appId: '1:76788598536:web:3082116fe542b8fc714ebd',
    messagingSenderId: '76788598536',
    projectId: 'binge-muzic',
    authDomain: 'binge-muzic.firebaseapp.com',
    storageBucket: 'binge-muzic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr1LkAq7UrEfJ65jMkoXxJf1g8CuTbE1U',
    appId: '1:76788598536:android:7c787959954afe0a714ebd',
    messagingSenderId: '76788598536',
    projectId: 'binge-muzic',
    storageBucket: 'binge-muzic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNn-8819RwbIq1G1WglHNPIyaxM486CI',
    appId: '1:76788598536:ios:ad6119ae99f253d8714ebd',
    messagingSenderId: '76788598536',
    projectId: 'binge-muzic',
    storageBucket: 'binge-muzic.appspot.com',
    iosBundleId: 'com.example.songz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPNn-8819RwbIq1G1WglHNPIyaxM486CI',
    appId: '1:76788598536:ios:7342ac0c9633e0ca714ebd',
    messagingSenderId: '76788598536',
    projectId: 'binge-muzic',
    storageBucket: 'binge-muzic.appspot.com',
    iosBundleId: 'com.example.songz.RunnerTests',
  );
}
